name: Python application

on:
  push:
    branches: [ "logger_w" ]

jobs:
  med-backend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Kill old app (if running)
      run: |
        pkill -f app.py || true

    - name: Start app
      run: |
        nohup python3 app.py &
